In [1]:
import numpy as np 
import seaborn as sns 
from scipy.stats import chi2_contingency
import pandas as pd

In [2]:
df = sns.load_dataset('titanic')

In [4]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [5]:

contingency_table = pd.crosstab(df['sex'],df['survived'])

In [6]:

contingency_table

survived    0    1
sex
female     81  233
male      468  109

In [10]:
chi2, p_value , dof , expected = chi2_contingency(contingency_table)

In [11]:
print(float(chi2))

260.71702016732104

In [12]:
print(float(p_value))

1.197357062775565e-58

In [13]:
print(dof)

1

In [16]:
print(expected)

[[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [17]:
alpha = 0.05

In [18]:
if p_value < alpha:
    print("we reject the null hypothesis and there is a significant relationship between gender and survival")
else:
    print("there is no connection")

we reject the null hypothesis and there is a significant relationship between gender and survivl